/*
  Biology Unit 4 — Cell Division, DNA & Cancer
  36 questions mapped to every learning target

  HOW TO ADD THESE TO YOUR APP:
  1. Go to your GitHub repo → click js/data.js → pencil icon to edit
  2. Find the line:  ],   (the closing bracket of the biology array — just before "english:")
  3. Paste all the question objects above that closing bracket
  4. Commit changes → live in ~2 minutes

  opts[0] is always the correct answer. The app shuffles automatically.
  Continue IDs from where existing biology questions end (b30 → b31, b32, ...)
*/

// ── LESSON 1: How are cancer cells different from normal cells? ──────────────

    {id:'b70', topic:'Mitosis', diff:'easy',
     q:'What is the primary purpose of mitosis?',
     opts:['To produce two genetically identical daughter cells for growth and repair',
           'To produce four haploid cells for reproduction',
           'To replicate DNA before cell division',
           'To exchange genetic material between homologous chromosomes'],
     exp:'Mitosis produces two diploid, genetically identical daughter cells used for growth, development, and tissue repair. Meiosis (not mitosis) produces gametes.'},

    {id:'b71', topic:'Cancer Biology', diff:'medium',
     q:'Which statement correctly describes the morphological difference between cancer cells and normal cells?',
     opts:['Cancer cells are often irregular in shape with large, dark-staining nuclei',
           'Cancer cells are smaller and more uniform than normal cells',
           'Cancer cells have more mitochondria and a smaller nucleus',
           'Cancer cells lack a cell membrane'],
     exp:'Cancer cells typically appear irregular in shape, have large nuclei with prominent nucleoli, and stain more darkly due to increased DNA content. Normal cells are uniform and orderly.'},

    {id:'b72', topic:'Cancer Biology', diff:'medium',
     q:'How do mitotic rates differ between cancer cells and normal cells?',
     opts:['Cancer cells divide more rapidly and without the normal controls that limit division',
           'Cancer cells divide more slowly than normal cells',
           'Cancer cells and normal cells divide at the same rate',
           'Cancer cells only divide once, then stop'],
     exp:'Cancer cells have lost the regulatory controls (checkpoints, contact inhibition) that limit division, so they divide continuously and at a much faster rate than normal cells.'},

    {id:'b73', topic:'Cancer Biology', diff:'medium',
     q:'What is apoptosis, and how does it differ in cancer cells?',
     opts:['Apoptosis is programmed cell death; cancer cells evade it and survive longer than they should',
           'Apoptosis is cell division; cancer cells undergo it more frequently',
           'Apoptosis is DNA repair; cancer cells perform it better than normal cells',
           'Apoptosis is cell growth; it is increased in cancer cells'],
     exp:'Apoptosis = controlled, programmed cell death. Normal cells die on schedule. Cancer cells disable apoptosis pathways, allowing damaged cells to survive and continue dividing.'},

    {id:'b74', topic:'Cancer Biology', diff:'hard',
     q:'What is contact inhibition, and what happens to it in cancer cells?',
     opts:['Contact inhibition is a process where normal cells stop dividing when they touch neighboring cells; cancer cells lose this ability',
           'Contact inhibition is when cells attract each other; cancer cells show increased contact inhibition',
           'Contact inhibition is apoptosis triggered by physical contact; it is enhanced in cancer',
           'Contact inhibition refers to immune cells blocking tumor growth'],
     exp:'Normal cells sense when they are crowded and stop dividing (contact inhibition). Cancer cells lose this signal — they continue to grow on top of each other, forming tumors.'},

// ── LESSON 2: How is the rate of cell division regulated? ────────────────────

    {id:'b75', topic:'Cell Cycle', diff:'easy',
     q:'What is the correct order of the major stages of the cell cycle?',
     opts:['G1 → S → G2 → M (mitosis)',
           'S → G1 → G2 → M (mitosis)',
           'M → G1 → S → G2',
           'G1 → G2 → S → M (mitosis)'],
     exp:'G1 (growth), S (DNA synthesis/replication), G2 (growth & prep), M (mitosis & cytokinesis). Together G1+S+G2 = interphase.'},

    {id:'b76', topic:'Cell Cycle', diff:'medium',
     q:'What is the role of cell cycle checkpoints?',
     opts:['To verify that each phase is completed correctly before allowing the cell to proceed to the next phase',
           'To speed up the cell cycle by skipping unnecessary steps',
           'To trigger apoptosis in all cells after division',
           'To copy DNA during the S phase'],
     exp:'Checkpoints (G1, G2, and spindle checkpoints) are quality-control stops. The cell only moves forward if conditions are met — DNA is undamaged, replication is complete, chromosomes are aligned.'},

    {id:'b77', topic:'Cell Cycle', diff:'medium',
     q:'What happens to cell cycle checkpoints in a cancer cell?',
     opts:['Checkpoints are bypassed or disabled, allowing cells with damaged DNA to continue dividing',
           'Checkpoints are strengthened, causing cancer cells to divide more carefully',
           'Checkpoints trigger extra rounds of DNA replication in cancer cells',
           'Checkpoints are unaffected — only apoptosis changes in cancer'],
     exp:'Mutations in checkpoint proteins (like p53) disable these quality controls. Cancer cells bypass checkpoints, allowing cells with damaged or mutated DNA to keep dividing and passing errors to daughter cells.'},

    {id:'b78', topic:'Cell Cycle', diff:'medium',
     q:'What is the role of apoptosis in the normal cell life cycle?',
     opts:['It eliminates damaged, infected, or no-longer-needed cells in a controlled way',
           'It triggers cell division when nutrients are available',
           'It repairs damaged DNA before the cell divides',
           'It copies DNA during the S phase'],
     exp:'Apoptosis is the cell\'s built-in self-destruct mechanism. It removes cells that are damaged beyond repair, potentially cancerous, or simply no longer needed (e.g., cells between fingers during development).'},

    {id:'b79', topic:'Cell Cycle', diff:'hard',
     q:'What is the role of the p53 protein in the cell cycle?',
     opts:['p53 acts as a tumor suppressor — it detects DNA damage and either halts the cell cycle for repair or triggers apoptosis',
           'p53 promotes rapid cell division by activating growth genes',
           'p53 is an enzyme that replicates DNA during the S phase',
           'p53 forms the spindle fibers that separate chromosomes during mitosis'],
     exp:'p53 is called the "guardian of the genome." When it detects DNA damage, it pauses the cell cycle at the G1 checkpoint to allow repair. If damage is too severe, p53 triggers apoptosis. Mutated p53 is found in ~50% of human cancers.'},

// ── LESSON 3: Why do we have different types of cells? ───────────────────────

    {id:'b80', topic:'Cell Differentiation', diff:'medium',
     q:'Which types of cells primarily undergo mitosis in an adult human?',
     opts:['Somatic (body) cells such as skin, intestinal lining, and blood cells',
           'Neurons (nerve cells) — they divide constantly throughout life',
           'Red blood cells — they divide to replace themselves',
           'Only embryonic cells undergo mitosis; adult cells do not'],
     exp:'Most adult somatic cells can undergo mitosis, especially those that need frequent replacement (skin, gut lining, blood cells). Neurons and muscle cells rarely divide. Red blood cells have no nucleus and cannot divide.'},

    {id:'b81', topic:'Cell Differentiation', diff:'medium',
     q:'Why do skin cells divide much more frequently than liver cells?',
     opts:['Skin cells are continuously shed and need rapid replacement; liver cells are replaced slowly',
           'Skin cells have more DNA, so they replicate faster',
           'Liver cells have lost the ability to divide entirely',
           'Skin cells respond to hormones that speed up mitosis in all cell types'],
     exp:'Different cell types have very different mitotic rates based on their function. Skin and intestinal cells turn over rapidly (days to weeks). Liver cells regenerate on demand. Neurons in the brain rarely divide at all.'},

    {id:'b82', topic:'Cell Differentiation', diff:'easy',
     q:'What is cell differentiation?',
     opts:['The process by which cells with identical DNA develop into specialized cell types with distinct structures and functions',
           'The process of a cell dividing into two identical daughter cells',
           'The mutation of DNA that causes cells to become cancerous',
           'The death of cells that are no longer needed by the body'],
     exp:'All cells in your body have the same DNA, but gene expression differs. Differentiation = cells "switching on" specific genes so a skin cell looks and behaves differently from a neuron or a muscle cell.'},

    {id:'b83', topic:'Stem Cells', diff:'medium',
     q:'What is the role of stem cells in complex organisms?',
     opts:['Stem cells are undifferentiated cells that can divide and develop into specialized cell types to build and maintain tissues',
           'Stem cells are fully differentiated cells that cannot divide further',
           'Stem cells only exist in embryos and disappear after birth',
           'Stem cells are a type of cancer cell that divides without control'],
     exp:'Stem cells are the body\'s "master cells." They self-renew and can differentiate into specialized cells. Embryonic stem cells can become any cell type; adult stem cells (e.g., bone marrow) replace specific tissues throughout life.'},

    {id:'b84', topic:'Stem Cells', diff:'hard',
     q:'Which best describes regeneration as it relates to stem cells?',
     opts:['Regeneration is the ability of some organisms to regrow lost tissues or organs, powered by stem cells that differentiate into needed cell types',
           'Regeneration refers to DNA repair during the S phase of the cell cycle',
           'Regeneration is the process of making copies of a gene in the lab',
           'Regeneration describes when cancer cells revert to normal cell behavior'],
     exp:'Salamanders can regrow limbs; humans regenerate liver tissue — both involve stem cells proliferating and differentiating. The extent of regeneration depends on how many stem cells are available and how they are activated.'},

// ── LESSON 4: How do cells replicate their DNA? ──────────────────────────────

    {id:'b85', topic:'DNA Replication', diff:'easy',
     q:'Which are the four components that make up the structure of a DNA nucleotide?',
     opts:['A phosphate group, deoxyribose sugar, and one of four nitrogenous bases (A, T, G, or C)',
           'A ribose sugar, phosphate group, and one of four bases (A, U, G, or C)',
           'A glucose molecule, amino acid, and a nitrogenous base',
           'A phospholipid, nitrogen base, and a carbohydrate'],
     exp:'DNA nucleotide = phosphate + deoxyribose sugar + nitrogenous base. The four bases: Adenine (A), Thymine (T), Guanine (G), Cytosine (C). RNA uses ribose and Uracil instead of Thymine.'},

    {id:'b86', topic:'DNA Replication', diff:'medium',
     q:'What is the role of helicase in DNA replication?',
     opts:['Helicase unwinds and separates the two strands of the DNA double helix at the replication fork',
           'Helicase adds new complementary nucleotides to the growing DNA strand',
           'Helicase seals the gaps (nicks) between Okazaki fragments on the lagging strand',
           'Helicase synthesizes a short RNA primer to start replication'],
     exp:'Helicase breaks the hydrogen bonds between complementary base pairs, "unzipping" the double helix to expose the template strands. Think of it as a molecular zipper-opener.'},

    {id:'b87', topic:'DNA Replication', diff:'medium',
     q:'What is the role of primase in DNA replication?',
     opts:['Primase synthesizes a short RNA primer that gives DNA polymerase a starting point',
           'Primase unwinds the double helix at the replication fork',
           'Primase connects the sugar-phosphate backbone between Okazaki fragments',
           'Primase proofreads the newly synthesized DNA for errors'],
     exp:'DNA polymerase can only add nucleotides to an existing strand — it cannot start from scratch. Primase lays down a short RNA primer (5–10 nucleotides) that DNA polymerase then extends.'},

    {id:'b88', topic:'DNA Replication', diff:'medium',
     q:'What is the role of DNA polymerase in DNA replication?',
     opts:['DNA polymerase reads the template strand and adds complementary nucleotides to synthesize a new DNA strand in the 5\'→3\' direction',
           'DNA polymerase unzips the double helix by breaking hydrogen bonds',
           'DNA polymerase removes the RNA primers after replication',
           'DNA polymerase joins the two new DNA molecules together after replication'],
     exp:'DNA polymerase is the main replication enzyme — it builds the new strand by adding nucleotides (A with T, G with C) and also proofreads for errors. It can only work 5\'→3\'.'},

    {id:'b89', topic:'DNA Replication', diff:'medium',
     q:'What is the role of DNA ligase in DNA replication?',
     opts:['Ligase joins (seals) the gaps between Okazaki fragments on the lagging strand, completing the new DNA strand',
           'Ligase unwinds the DNA double helix to expose the template strands',
           'Ligase synthesizes the RNA primers used to start DNA synthesis',
           'Ligase adds nucleotides to the leading strand during replication'],
     exp:'The lagging strand is synthesized in fragments (Okazaki fragments). After the RNA primers are removed, ligase acts like molecular glue — sealing the nicks in the sugar-phosphate backbone to create a continuous strand.'},

    {id:'b90', topic:'DNA Replication', diff:'hard',
     q:"What does it mean for DNA strands to be anti-parallel?",
     opts:["The two strands run in opposite directions — one runs 5'→3' and the other runs 3'→5'",
           "The two strands have the same base sequence but different chemical compositions",
           "The two strands separate completely during replication and never rejoin",
           "Anti-parallel means the strands repel each other magnetically"],
     exp:"Each DNA strand has a 5' end (phosphate) and a 3' end (hydroxyl). The two strands are oriented oppositely: if one runs 5'→3' top-to-bottom, the complementary strand runs 3'→5' top-to-bottom. This is why the lagging strand is copied in fragments."},

    {id:'b91', topic:'DNA Replication', diff:'hard',
     q:'What does "semi-conservative replication" mean?',
     opts:['Each new DNA molecule consists of one original (parental) strand and one newly synthesized strand',
           'Only half of the DNA molecule is copied during each round of replication',
           'The original DNA molecule is completely destroyed and two entirely new copies are made',
           'Semi-conservative means replication only happens in the S phase'],
     exp:'Meselson-Stahl (1958) confirmed: after replication, each daughter DNA double helix keeps one original strand paired with one new strand. "Semi" = half old, half new.'},

    {id:'b92', topic:'DNA Replication', diff:'easy',
     q:'What are the base-pairing rules for DNA?',
     opts:['Adenine (A) pairs with Thymine (T); Guanine (G) pairs with Cytosine (C)',
           'Adenine (A) pairs with Guanine (G); Thymine (T) pairs with Cytosine (C)',
           'Adenine (A) pairs with Cytosine (C); Guanine (G) pairs with Thymine (T)',
           'All four bases can pair with any other base'],
     exp:'A–T pairs are held by 2 hydrogen bonds; G–C pairs by 3 hydrogen bonds. This complementary base pairing is what allows accurate DNA replication and RNA synthesis.'},

// ── LESSON 5: What is Central Dogma? ────────────────────────────────────────

    {id:'b93', topic:'Central Dogma', diff:'easy',
     q:'Where does transcription occur in a eukaryotic cell?',
     opts:['In the nucleus, where DNA is located',
           'In the cytoplasm, at the ribosome',
           'In the mitochondria only',
           'In the endoplasmic reticulum'],
     exp:'Transcription happens in the nucleus — RNA polymerase reads the DNA template and produces mRNA. The mRNA then travels to the cytoplasm for translation.'},

    {id:'b94', topic:'Central Dogma', diff:'easy',
     q:'Where does translation occur in a eukaryotic cell?',
     opts:['In the cytoplasm, at ribosomes',
           'In the nucleus, where DNA is located',
           'In the Golgi apparatus',
           'In the smooth endoplasmic reticulum'],
     exp:'Translation occurs at ribosomes in the cytoplasm (or on the rough ER). Ribosomes read the mRNA codons and assemble the amino acid chain (polypeptide).'},

    {id:'b95', topic:'Central Dogma', diff:'medium',
     q:'Which best describes the process of transcription?',
     opts:['RNA polymerase reads a DNA template strand and synthesizes a complementary mRNA strand',
           'Ribosomes read the mRNA and assemble a chain of amino acids',
           'DNA polymerase copies both strands of DNA to produce two identical DNA molecules',
           'tRNA carries amino acids to the ribosome for assembly into proteins'],
     exp:'Transcription: DNA → mRNA. RNA polymerase unwinds the DNA, reads the template 3\'→5\', and builds mRNA 5\'→3\' using complementary base pairing (except U replaces T in RNA).'},

    {id:'b96', topic:'Central Dogma', diff:'medium',
     q:'Which best describes the process of translation?',
     opts:['Ribosomes read mRNA codons and tRNA molecules deliver matching amino acids to build a polypeptide chain',
           'RNA polymerase reads DNA and produces an mRNA copy',
           'DNA is replicated using helicase and DNA polymerase',
           'The polypeptide chain folds into a 3D protein shape'],
     exp:'Translation: mRNA → protein. Ribosome reads each 3-nucleotide codon; tRNA anticodons match and deliver the correct amino acid; the growing polypeptide chain is released at a stop codon.'},

    {id:'b97', topic:'Central Dogma', diff:'hard',
     q:'Using the codon chart: what amino acid does the codon AUG code for?',
     opts:['Methionine (Met) — it is also the universal start codon',
           'Leucine (Leu)',
           'Valine (Val)',
           'It is a stop codon'],
     exp:'AUG codes for methionine AND serves as the universal start codon — every protein begins with AUG. UAA, UAG, and UGA are the three stop codons.'},

    {id:'b98', topic:'Central Dogma', diff:'hard',
     q:'How do amino acid side chains (R groups) determine protein folding?',
     opts:['Interactions between R groups (hydrogen bonds, ionic bonds, hydrophobic interactions) cause the polypeptide to fold into a specific 3D shape',
           'All amino acids have identical R groups, so folding is random',
           'Protein folding is determined only by the DNA sequence, not by amino acids',
           'R groups only affect the color of the protein, not its shape'],
     exp:'Each amino acid has a unique R group that is polar, nonpolar, charged, or hydrophobic. These properties drive folding: hydrophobic R groups cluster inside, charged ones face outward toward water. Shape = function.'},

    {id:'b99', topic:'Central Dogma', diff:'hard',
     q:'Why is correct protein folding essential for function?',
     opts:['The specific 3D shape of a protein determines its active site and ability to interact with other molecules',
           'Protein folding only affects how proteins are transported out of the cell',
           'Misfolded proteins are always repaired automatically by ribosomes',
           'Protein shape has no effect on function — only the amino acid sequence matters'],
     exp:'Protein function depends entirely on shape. Enzymes, antibodies, hormones — all rely on a precise 3D structure to bind their targets. Misfolded proteins can\'t function and may aggregate (as in Alzheimer\'s or Parkinson\'s disease).'},

// ── LESSON 6: How does a mutation lead to a change in protein? ───────────────

    {id:'b100', topic:'Mutations', diff:'easy',
     q:'What is a substitution mutation?',
     opts:['One nucleotide base is replaced by a different base in the DNA sequence',
           'One or more nucleotide bases are added to the DNA sequence',
           'One or more nucleotide bases are removed from the DNA sequence',
           'Two chromosomes exchange segments of DNA'],
     exp:'Substitution (point mutation): one base swaps for another (e.g., A→G). May change an amino acid (missense), create a stop codon (nonsense), or have no effect (silent mutation).'},

    {id:'b101', topic:'Mutations', diff:'medium',
     q:'Why are insertion and deletion mutations often more damaging than substitution mutations?',
     opts:['Insertions and deletions cause a frameshift — all codons downstream are read in the wrong frame, scrambling the entire protein',
           'Insertions and deletions only affect a single amino acid, making the damage minor',
           'Substitutions always create stop codons, which is more harmful',
           'Insertions and deletions only occur in non-coding DNA and have no effect'],
     exp:'Codons are read in groups of 3. Adding or removing a base shifts the reading frame for every codon that follows — like removing a letter from a sentence and re-reading: "THE CAT SAT" → "TEC ATS AT." The entire protein downstream is scrambled.'},

    {id:'b102', topic:'Mutations', diff:'medium',
     q:'How does a mutation in DNA lead to a change in protein structure?',
     opts:['A changed DNA sequence → different mRNA codon during transcription → different amino acid delivered during translation → altered polypeptide that may fold differently',
           'A mutation directly changes the shape of a finished protein without affecting the DNA',
           'Mutations only affect DNA replication, not protein synthesis',
           'A mutation changes the ribosome, not the mRNA or amino acid sequence'],
     exp:'The pathway: mutated DNA → altered mRNA codon (transcription) → wrong amino acid inserted (translation) → polypeptide with changed R groups → different folding → altered or lost function.'},

    {id:'b103', topic:'Mutations', diff:'hard',
     q:'What happens to the cell cycle if the p53 gene is mutated?',
     opts:['The G1 checkpoint fails — cells with damaged DNA bypass quality control and continue dividing, accumulating more mutations',
           'The cell cycle speeds up temporarily, then returns to normal',
           'The cell immediately undergoes apoptosis when p53 is mutated',
           'Mutated p53 causes cells to stop dividing permanently'],
     exp:'Normally p53 halts the cycle at G1 to allow DNA repair, or triggers apoptosis if damage is irreparable. A mutated p53 protein cannot bind DNA or activate these pathways — damaged cells keep dividing, which is a hallmark of cancer.'},

    {id:'b104', topic:'Mutations', diff:'hard',
     q:'How can a single nucleotide substitution in a gene lead to a completely non-functional protein?',
     opts:['The substitution may create a premature stop codon, producing a truncated protein that cannot fold or function correctly',
           'A single substitution never affects protein function — only large deletions do',
           'The substitution changes only the DNA, not the mRNA, so the protein is unaffected',
           'Ribosomes detect single-base substitutions and correct them before translation'],
     exp:'A nonsense mutation (substitution creating a stop codon — e.g., UAU→UAA) truncates the polypeptide chain prematurely. The short, misfolded fragment almost always loses function. Sickle cell disease is a missense example: one A→T substitution changes Glu→Val in hemoglobin.'},

// ── LESSON 7: How do external factors lead to cancer? ────────────────────────

    {id:'b105', topic:'Cancer Biology', diff:'easy',
     q:'What is a mutagen?',
     opts:['Any physical, chemical, or biological agent that increases the rate of mutations in DNA',
           'A protein that repairs DNA damage caused by radiation',
           'A type of cell that destroys cancer cells in the immune system',
           'An enzyme that corrects errors during DNA replication'],
     exp:'Mutagens cause DNA mutations that can potentially lead to cancer. Examples: UV radiation (melanoma), tobacco smoke (lung cancer), certain chemicals, and some viruses (HPV → cervical cancer).'},

    {id:'b106', topic:'Cancer Biology', diff:'medium',
     q:'How can UV radiation from the sun cause skin cancer?',
     opts:['UV radiation causes thymine dimers — covalent bonds between adjacent thymine bases — that distort the DNA and can cause mutations if not repaired',
           'UV radiation directly destroys cancer cells, but also damages healthy cells',
           'UV radiation inserts extra nucleotides into the DNA, causing frameshift mutations',
           'UV radiation only damages the cell membrane, not the DNA itself'],
     exp:'UV-B radiation causes adjacent thymine bases to bond together (thymine dimers), distorting the DNA. Normally repaired by nucleotide excision repair — but if mutations accumulate in genes like p53, skin cancer can develop.'},

    {id:'b107', topic:'Cancer Biology', diff:'medium',
     q:'Which of the following is the best example of a chemical mutagen?',
     opts:['The carcinogens in tobacco smoke, which bind to DNA and cause base substitutions',
           'Visible light from a lamp',
           'Cold temperatures that slow cell division',
           'Increased oxygen levels in the blood'],
     exp:'Tobacco smoke contains polycyclic aromatic hydrocarbons (PAHs) and other chemicals that bind to DNA bases, causing substitution mutations. This is why smoking dramatically increases the risk of lung, throat, and many other cancers.'},

    {id:'b108', topic:'Cancer Biology', diff:'hard',
     q:'Why does it usually take multiple mutations — not just one — for a normal cell to become cancerous?',
     opts:['Cancer requires mutations in multiple control systems simultaneously: cell cycle checkpoints, apoptosis pathways, growth factor signaling, and DNA repair genes',
           'One mutation is always sufficient to cause cancer if it occurs in p53',
           'The immune system prevents the first mutation from having any effect',
           'Multiple mutations are needed only for blood cancers, not solid tumors'],
     exp:'Cancer is a multi-step process. A cell needs to: bypass checkpoints, disable apoptosis, ignore "stop dividing" signals, activate growth genes, and eventually invade other tissues. Each step requires a separate mutation — which is why cancer risk increases with age (more time for mutations to accumulate).'},
