/* data.js — Question bank (150 Qs) + resources */

/* opts[0] is ALWAYS the correct answer. App shuffles before display. */

const SUBJECTS = {
  algebra2: { name:'Algebra 2 Honors',              short:'Algebra 2', emoji:'📐', color:'#6251DE' },
  biology:  { name:'Biology Honors',                short:'Biology',   emoji:'🧬', color:'#27AE60' },
  english:  { name:'English 9 Honors',              short:'English',   emoji:'📚', color:'#E6811E' },
  apCSP:    { name:'AP Computer Science Principles', short:'AP CSP',   emoji:'💻', color:'#E84C3C' },
  spanish2: { name:'Spanish 2',                      short:'Spanish 2',emoji:'🌎', color:'#D4A017' },
};

const QUESTION_BANK = {
  algebra2: [
    {id:'a1', topic:'Quadratic Functions', diff:'medium',
     q:'What is the discriminant of 2x² − 5x + 3 = 0?',
     opts:['1','−1','49','25'],
     exp:'Δ = b²−4ac = 25−24 = 1. Since Δ > 0, two real roots.'},
    {id:'a2', topic:'Quadratic Functions', diff:'medium',
     q:'What is the vertex of f(x) = x² − 6x + 8?',
     opts:['(3, −1)','(−3, 1)','(3, 1)','(6, 8)'],
     exp:'x = −b/2a = 3; f(3) = 9−18+8 = −1. Vertex is (3, −1).'},
    {id:'a3', topic:'Quadratic Functions', diff:'easy',
     q:'Which form of a quadratic directly shows the vertex?',
     opts:['Vertex form: a(x−h)² + k','Standard form: ax² + bx + c','Intercept form','General form'],
     exp:'In vertex form a(x−h)²+k, the vertex is (h, k) by inspection.'},
    {id:'a4', topic:'Polynomials', diff:'easy',
     q:'What is the degree of 3x⁴ − 2x³ + x − 7?',
     opts:['4','3','1','7'],
     exp:'The degree is the highest exponent, which is 4.'},
    {id:'a5', topic:'Polynomials', diff:'easy',
     q:'Factor completely: 4x² − 9',
     opts:['(2x+3)(2x−3)','(4x−3)(x+3)','(2x−3)²','(4x+3)(x−3)'],
     exp:'Difference of squares: a²−b² = (a+b)(a−b) with a=2x, b=3.'},
    {id:'a6', topic:'Polynomials', diff:'hard',
     q:"By the Rational Root Theorem, which is NOT a possible zero of 2x³−3x+1?",
     opts:['3/2','1','−1','1/2'],
     exp:'Possible zeros = ±(factors of 1)/(factors of 2) = ±1, ±1/2. 3/2 is not in this list.'},
    {id:'a7', topic:'Exponential Functions', diff:'easy',
     q:'Solve: 2ˣ = 32',
     opts:['5','4','6','16'],
     exp:'2⁵ = 32, so x = 5.'},
    {id:'a8', topic:'Exponential Functions', diff:'medium',
     q:'Evaluate f(x) = 2ˣ at x = −3.',
     opts:['1/8','−8','−1/8','8'],
     exp:'2⁻³ = 1/2³ = 1/8.'},
    {id:'a9', topic:'Logarithms', diff:'easy',
     q:'Evaluate log₂(64).',
     opts:['6','8','4','32'],
     exp:'2⁶ = 64, so log₂(64) = 6.'},
    {id:'a10', topic:'Logarithms', diff:'easy',
     q:'Evaluate log(100).',
     opts:['2','10','1','100'],
     exp:'log₁₀(10²) = 2.'},
    {id:'a11', topic:'Logarithms', diff:'easy',
     q:'Evaluate ln(e⁵).',
     opts:['5','e⁵','1','5e'],
     exp:'ln and e are inverse functions, so ln(e⁵) = 5.'},
    {id:'a12', topic:'Logarithms', diff:'medium',
     q:'Convert to exponential form: log₅(x) = 3',
     opts:['5³ = x','x³ = 5','3⁵ = x','x = 15'],
     exp:'logₐ(b) = c ↔ aᶜ = b, so log₅(x) = 3 ↔ 5³ = x.'},
    {id:'a13', topic:'Sequences & Series', diff:'medium',
     q:'An arithmetic sequence has first term 3, common difference 4. What is the 10th term?',
     opts:['39','43','36','40'],
     exp:'aₙ = a₁+(n−1)d = 3+9(4) = 39.'},
    {id:'a14', topic:'Sequences & Series', diff:'medium',
     q:'What is the sum of the infinite geometric series 4+2+1+½+…?',
     opts:['8','4','∞','6'],
     exp:'S = a/(1−r) = 4/(1−0.5) = 8. Valid since |r| = 0.5 < 1.'},
    {id:'a15', topic:'Sequences & Series', diff:'medium',
     q:'A geometric sequence has first term 2 and ratio 3. What is the 5th term?',
     opts:['162','54','486','81'],
     exp:'a₅ = 2·3⁴ = 2·81 = 162.'},
    {id:'a16', topic:'Conic Sections', diff:'medium',
     q:'Which conic section does x²/9 + y²/4 = 1 describe?',
     opts:['Ellipse','Hyperbola','Circle','Parabola'],
     exp:'Same-sign terms with different denominators → ellipse.'},
    {id:'a17', topic:'Conic Sections', diff:'medium',
     q:'Equation of a circle with center (2, −3) and radius 5?',
     opts:['(x−2)²+(y+3)²=25','(x+2)²+(y−3)²=25','(x−2)²+(y+3)²=5','(x−2)²+(y−3)²=25'],
     exp:'Standard form: (x−h)²+(y−k)²=r². Center (2,−3), r²=25.'},
    {id:'a18', topic:'Rational Expressions', diff:'medium',
     q:'Simplify (x²−4)/(x−2), state any restrictions.',
     opts:['x+2, x≠2','x−2','x²−4','x+2 for all x'],
     exp:'x²−4=(x+2)(x−2). Cancel (x−2): x+2, with x≠2 excluded.'},
    {id:'a19', topic:'Functions', diff:'medium',
     q:'If f(x) = 3x+2 and g(x) = x², find f(g(x)).',
     opts:['3x²+2','(3x+2)²','9x²+12x+4','x²+2'],
     exp:'f(g(x)) = f(x²) = 3(x²)+2 = 3x²+2.'},
    {id:'a20', topic:'Functions', diff:'medium',
     q:'Find the inverse of f(x) = 2x − 6.',
     opts:['f⁻¹(x) = (x+6)/2','f⁻¹(x) = 2x+6','f⁻¹(x) = (x−6)/2','f⁻¹(x) = 1/(2x−6)'],
     exp:'Swap x and y: x = 2y−6 → y = (x+6)/2.'},
    {id:'a21', topic:'Radical Functions', diff:'easy',
     q:'What is the domain of f(x) = √(x − 4)?',
     opts:['x ≥ 4','x > 4','x ≤ 4','All real numbers'],
     exp:'Radicand must be ≥ 0: x−4 ≥ 0 → x ≥ 4.'},
    {id:'a22', topic:'Absolute Value', diff:'medium',
     q:'Solve |2x − 3| = 7.',
     opts:['x=5 or x=−2','x=5','x=−2','x=±5'],
     exp:'2x−3=7 → x=5; and 2x−3=−7 → x=−2.'},
    {id:'a23', topic:'Polynomials', diff:'easy',
     q:'What are the roots of x²−5x+6 = 0?',
     opts:['x=2 and x=3','x=−2 and x=−3','x=1 and x=6','x=5 and x=6'],
     exp:'Factor: (x−2)(x−3) = 0, so x=2 or x=3.'},
    {id:'a24', topic:'Logarithms', diff:'easy',
     q:'Using log properties, simplify log(ab).',
     opts:['log(a) + log(b)','log(a)·log(b)','log(a)−log(b)','log(a/b)'],
     exp:'Product rule: logₐ(xy) = logₐ(x)+logₐ(y).'},
    {id:'a25', topic:'Statistics', diff:'medium',
     q:'In a normal distribution, ~what % of data falls within one standard deviation?',
     opts:['68%','95%','50%','99.7%'],
     exp:'68-95-99.7 rule: 68% within 1σ, 95% within 2σ, 99.7% within 3σ.'},
    {id:'a26', topic:'Functions', diff:'easy',
     q:'What is the range of f(x) = x²?',
     opts:['y ≥ 0','All real numbers','y > 0','y ≤ 0'],
     exp:'x² is always non-negative, so range is y ≥ 0.'},
    {id:'a27', topic:'Exponential Functions', diff:'medium',
     q:'Which equation models exponential decay?',
     opts:['y = a(1−r)ᵗ where 0<r<1','y = a(1+r)ᵗ where r>0','y = at+b','y = arᵗ where r>1'],
     exp:'Decay uses base between 0 and 1. Factor is (1−r) where r is decay rate.'},
    {id:'a28', topic:'Conic Sections', diff:'hard',
     q:'The equation x²/16 − y²/9 = 1 represents a:',
     opts:['Hyperbola','Ellipse','Circle','Parabola'],
     exp:'Different signs between x² and y² → hyperbola. Form: x²/a²−y²/b²=1.'},
    {id:'a29', topic:'Quadratic Functions', diff:'medium',
     q:'If the discriminant is negative, the quadratic has:',
     opts:['Two complex (non-real) roots','Two real roots','One real root','No roots at all'],
     exp:'Negative discriminant → √Δ is imaginary → two complex conjugate roots.'},
    {id:'a30', topic:'Sequences & Series', diff:'hard',
     q:'The Fibonacci sequence: 1,1,2,3,5,8,… What is the 9th term?',
     opts:['34','21','55','13'],
     exp:'Continuing: 13,21,34. The 9th term is 34.'},
  ],

  biology: [
    {id:'b1', topic:'Cell Structure', diff:'easy',
     q:"Which organelle is the 'powerhouse of the cell'?",
     opts:['Mitochondria','Ribosome','Golgi apparatus','Nucleus'],
     exp:'Mitochondria produce ATP through cellular respiration.'},
    {id:'b2', topic:'Cell Structure', diff:'easy',
     q:'Which organelle synthesizes proteins?',
     opts:['Ribosome','Mitochondria','Vacuole','Centrosome'],
     exp:'Ribosomes translate mRNA into proteins. They can be free-floating or ER-bound.'},
    {id:'b3', topic:'Cell Structure', diff:'easy',
     q:'The fluid mosaic model describes the structure of the:',
     opts:['Cell membrane','Cell wall','Nucleus','Cytoplasm'],
     exp:'Singer & Nicolson (1972) described the phospholipid bilayer with embedded proteins.'},
    {id:'b4', topic:'Photosynthesis', diff:'medium',
     q:'In which part of the chloroplast does the Calvin cycle occur?',
     opts:['Stroma','Thylakoid membrane','Outer membrane','Intermembrane space'],
     exp:'The Calvin cycle (light-independent reactions) occurs in the stroma.'},
    {id:'b5', topic:'Photosynthesis', diff:'easy',
     q:'What are the reactants of photosynthesis?',
     opts:['CO₂ + H₂O + light','C₆H₁₂O₆ + O₂','ATP + NADPH','CO₂ + O₂'],
     exp:'6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂'},
    {id:'b6', topic:'Cellular Respiration', diff:'medium',
     q:'Glycolysis produces how many NET ATP from one glucose?',
     opts:['2 ATP','32 ATP','4 ATP','38 ATP'],
     exp:'Glycolysis produces 4 ATP but uses 2, for a net gain of 2 ATP.'},
    {id:'b7', topic:'Cellular Respiration', diff:'easy',
     q:'The overall equation for aerobic respiration is:',
     opts:['C₆H₁₂O₆+6O₂→6CO₂+6H₂O+ATP','6CO₂+6H₂O→C₆H₁₂O₆+6O₂','ATP→ADP+Pᵢ+energy','C₆H₁₂O₆→2C₂H₅OH+2CO₂'],
     exp:'Aerobic respiration: glucose + oxygen → carbon dioxide + water + ATP.'},
    {id:'b8', topic:'Genetics', diff:'medium',
     q:'Monohybrid cross of two heterozygotes (Aa × Aa): expected phenotypic ratio?',
     opts:['3:1','1:2:1','1:1','All dominant'],
     exp:'Aa × Aa yields 1AA:2Aa:1aa. AA and Aa both show dominant trait → 3:1.'},
    {id:'b9', topic:'Genetics', diff:'medium',
     q:'A gene located on the X chromosome is described as:',
     opts:['X-linked (sex-linked)','Autosomal dominant','Autosomal recessive','Codominant'],
     exp:'Hemophilia and color blindness are classic X-linked traits.'},
    {id:'b10', topic:'DNA & Proteins', diff:'easy',
     q:'Which base pairs with adenine (A) in DNA?',
     opts:['Thymine (T)','Guanine (G)','Cytosine (C)','Uracil (U)'],
     exp:'In DNA: A pairs with T; G pairs with C. In RNA, A pairs with U.'},
    {id:'b11', topic:'DNA & Proteins', diff:'medium',
     q:'Which type of RNA carries amino acids to the ribosome during translation?',
     opts:['tRNA (transfer RNA)','mRNA (messenger RNA)','rRNA (ribosomal RNA)','snRNA'],
     exp:'tRNA has an anticodon that matches mRNA codons and carries the amino acid.'},
    {id:'b12', topic:'DNA & Proteins', diff:'medium',
     q:'RNA polymerase is the enzyme used in:',
     opts:['Transcription','Translation','Replication','Splicing'],
     exp:'RNA polymerase reads the DNA template and synthesizes complementary mRNA.'},
    {id:'b13', topic:'Cell Division', diff:'easy',
     q:'During which phase of mitosis do chromosomes align at the equator?',
     opts:['Metaphase','Prophase','Anaphase','Telophase'],
     exp:'Metaphase: chromosomes fully condensed and align at the metaphase plate.'},
    {id:'b14', topic:'Cell Division', diff:'medium',
     q:'Meiosis produces how many daughter cells, and are they haploid or diploid?',
     opts:['4 haploid cells','2 diploid cells','4 diploid cells','2 haploid cells'],
     exp:'Meiosis I and II together produce 4 genetically unique haploid (n) cells.'},
    {id:'b15', topic:'Evolution', diff:'easy',
     q:"Darwin's proposed mechanism for evolution is:",
     opts:['Natural selection','Genetic drift','Mutation','Gene flow'],
     exp:'Darwin: individuals with favorable traits survive and reproduce more — natural selection.'},
    {id:'b16', topic:'Evolution', diff:'hard',
     q:'Hardy-Weinberg equilibrium requires all EXCEPT:',
     opts:['Natural selection is occurring','Large population','Random mating','No mutation'],
     exp:'H-W requires: no selection, no mutation, large population, random mating, no gene flow.'},
    {id:'b17', topic:'Ecology', diff:'medium',
     q:"An organism's niche is best described as:",
     opts:['Its role and position in the ecosystem','The physical location where it lives','Its food source only','Its taxonomic classification'],
     exp:'A niche includes what an organism eats, where it lives, and how it interacts with others.'},
    {id:'b18', topic:'Ecology', diff:'easy',
     q:'Which type of ecological relationship benefits BOTH species?',
     opts:['Mutualism','Parasitism','Commensalism','Predation'],
     exp:'Mutualism: both benefit (e.g., bees and flowers, clownfish and anemone).'},
    {id:'b19', topic:'Biochemistry', diff:'easy',
     q:'DNA is made of monomers called:',
     opts:['Nucleotides','Amino acids','Monosaccharides','Fatty acids'],
     exp:'Nucleotides (phosphate + deoxyribose + base) are the monomers of DNA.'},
    {id:'b20', topic:'Biochemistry', diff:'medium',
     q:'Which macromolecule serves as primary long-term energy storage in animals?',
     opts:['Lipids (fats)','Carbohydrates','Proteins','Nucleic acids'],
     exp:'Lipids store more energy per gram and are the main long-term energy storage.'},
    {id:'b21', topic:'Cell Structure', diff:'easy',
     q:'The movement of water across a semipermeable membrane is called:',
     opts:['Osmosis','Diffusion','Active transport','Endocytosis'],
     exp:'Osmosis: passive water movement from low solute to high solute concentration.'},
    {id:'b22', topic:'Genetics', diff:'hard',
     q:'In codominance, red (RR) × white (WW) flower offspring are:',
     opts:['Both red and white on same flower','Pink (blend)','All red','All white'],
     exp:'In codominance both alleles are fully expressed — RW plants show patches of both colors.'},
    {id:'b23', topic:'Human Systems', diff:'medium',
     q:'Which organ produces insulin to regulate blood sugar?',
     opts:['Pancreas','Liver','Kidney','Adrenal gland'],
     exp:'Beta cells of the pancreatic islets of Langerhans produce insulin.'},
    {id:'b24', topic:'Cell Division', diff:'medium',
     q:'A mutation in a somatic (body) cell:',
     opts:['Cannot be inherited by offspring','Will be passed to next generation','Always causes cancer','Occurs only in skin cells'],
     exp:'Only mutations in gametes (eggs/sperm) can be inherited.'},
    {id:'b25', topic:'Evolution', diff:'hard',
     q:'Which provides the MOST direct evidence of common ancestry between species?',
     opts:['Homologous structures','Analogous structures','Convergent evolution','Vestigial organs'],
     exp:'Homologous structures (e.g., human arm and whale flipper) share the same ancestral blueprint.'},
    {id:'b26', topic:'Biochemistry', diff:'easy',
     q:'Enzymes are biological catalysts made of:',
     opts:['Proteins','Lipids','Carbohydrates','Nucleic acids'],
     exp:'Enzymes are proteins whose 3D active site binds substrates and lowers activation energy.'},
    {id:'b27', topic:'Ecology', diff:'hard',
     q:'Primary succession occurs on:',
     opts:['Bare rock with no soil or organisms','Land cleared by fire','Abandoned farmland','Flood-damaged wetlands'],
     exp:'Primary succession begins on substrate with no soil — like volcanic rock. Pioneer species build soil.'},
    {id:'b28', topic:'DNA & Proteins', diff:'medium',
     q:'The DNA double helix model was proposed by:',
     opts:['Watson and Crick (1953)','Darwin and Wallace','Mendel and Morgan','Pasteur and Koch'],
     exp:'Watson and Crick, using X-ray data from Rosalind Franklin, published the double helix in 1953.'},
    {id:'b29', topic:'Cell Structure', diff:'easy',
     q:'Which is found in plant cells but NOT animal cells?',
     opts:['Cell wall and large central vacuole','Mitochondria','Ribosomes','Cell membrane'],
     exp:'Plant cells have a rigid cellulose cell wall and a large central vacuole. Animal cells have neither.'},
    {id:'b30', topic:'Cellular Respiration', diff:'hard',
     q:'Where does the Krebs cycle take place?',
     opts:['Mitochondrial matrix','Inner mitochondrial membrane','Cytoplasm','Thylakoid membrane'],
     exp:'The Krebs (citric acid) cycle occurs in the mitochondrial matrix, following pyruvate oxidation.'},
    // ── LESSON 1: How are cancer cells different from normal cells? ──────────────

    {id:'b31', topic:'Mitosis', diff:'easy',
     q:'What is the primary purpose of mitosis?',
     opts:['To produce two genetically identical daughter cells for growth and repair',
           'To produce four haploid cells for reproduction',
           'To replicate DNA before cell division',
           'To exchange genetic material between homologous chromosomes'],
     exp:'Mitosis produces two diploid, genetically identical daughter cells used for growth, development, and tissue repair. Meiosis (not mitosis) produces gametes.'},

    {id:'b32', topic:'Cancer Biology', diff:'medium',
     q:'Which statement correctly describes the morphological difference between cancer cells and normal cells?',
     opts:['Cancer cells are often irregular in shape with large, dark-staining nuclei',
           'Cancer cells are smaller and more uniform than normal cells',
           'Cancer cells have more mitochondria and a smaller nucleus',
           'Cancer cells lack a cell membrane'],
     exp:'Cancer cells typically appear irregular in shape, have large nuclei with prominent nucleoli, and stain more darkly due to increased DNA content. Normal cells are uniform and orderly.'},

    {id:'b33', topic:'Cancer Biology', diff:'medium',
     q:'How do mitotic rates differ between cancer cells and normal cells?',
     opts:['Cancer cells divide more rapidly and without the normal controls that limit division',
           'Cancer cells divide more slowly than normal cells',
           'Cancer cells and normal cells divide at the same rate',
           'Cancer cells only divide once, then stop'],
     exp:'Cancer cells have lost the regulatory controls (checkpoints, contact inhibition) that limit division, so they divide continuously and at a much faster rate than normal cells.'},

    {id:'b34', topic:'Cancer Biology', diff:'medium',
     q:'What is apoptosis, and how does it differ in cancer cells?',
     opts:['Apoptosis is programmed cell death; cancer cells evade it and survive longer than they should',
           'Apoptosis is cell division; cancer cells undergo it more frequently',
           'Apoptosis is DNA repair; cancer cells perform it better than normal cells',
           'Apoptosis is cell growth; it is increased in cancer cells'],
     exp:'Apoptosis = controlled, programmed cell death. Normal cells die on schedule. Cancer cells disable apoptosis pathways, allowing damaged cells to survive and continue dividing.'},

    {id:'b35', topic:'Cancer Biology', diff:'hard',
     q:'What is contact inhibition, and what happens to it in cancer cells?',
     opts:['Contact inhibition is a process where normal cells stop dividing when they touch neighboring cells; cancer cells lose this ability',
           'Contact inhibition is when cells attract each other; cancer cells show increased contact inhibition',
           'Contact inhibition is apoptosis triggered by physical contact; it is enhanced in cancer',
           'Contact inhibition refers to immune cells blocking tumor growth'],
     exp:'Normal cells sense when they are crowded and stop dividing (contact inhibition). Cancer cells lose this signal — they continue to grow on top of each other, forming tumors.'},

// ── LESSON 2: How is the rate of cell division regulated? ────────────────────

    {id:'b36', topic:'Cell Cycle', diff:'easy',
     q:'What is the correct order of the major stages of the cell cycle?',
     opts:['G1 → S → G2 → M (mitosis)',
           'S → G1 → G2 → M (mitosis)',
           'M → G1 → S → G2',
           'G1 → G2 → S → M (mitosis)'],
     exp:'G1 (growth), S (DNA synthesis/replication), G2 (growth & prep), M (mitosis & cytokinesis). Together G1+S+G2 = interphase.'},

    {id:'b37', topic:'Cell Cycle', diff:'medium',
     q:'What is the role of cell cycle checkpoints?',
     opts:['To verify that each phase is completed correctly before allowing the cell to proceed to the next phase',
           'To speed up the cell cycle by skipping unnecessary steps',
           'To trigger apoptosis in all cells after division',
           'To copy DNA during the S phase'],
     exp:'Checkpoints (G1, G2, and spindle checkpoints) are quality-control stops. The cell only moves forward if conditions are met — DNA is undamaged, replication is complete, chromosomes are aligned.'},

    {id:'b38', topic:'Cell Cycle', diff:'medium',
     q:'What happens to cell cycle checkpoints in a cancer cell?',
     opts:['Checkpoints are bypassed or disabled, allowing cells with damaged DNA to continue dividing',
           'Checkpoints are strengthened, causing cancer cells to divide more carefully',
           'Checkpoints trigger extra rounds of DNA replication in cancer cells',
           'Checkpoints are unaffected — only apoptosis changes in cancer'],
     exp:'Mutations in checkpoint proteins (like p53) disable these quality controls. Cancer cells bypass checkpoints, allowing cells with damaged or mutated DNA to keep dividing and passing errors to daughter cells.'},

    {id:'b39', topic:'Cell Cycle', diff:'medium',
     q:'What is the role of apoptosis in the normal cell life cycle?',
     opts:['It eliminates damaged, infected, or no-longer-needed cells in a controlled way',
           'It triggers cell division when nutrients are available',
           'It repairs damaged DNA before the cell divides',
           'It copies DNA during the S phase'],
     exp:'Apoptosis is the cell\'s built-in self-destruct mechanism. It removes cells that are damaged beyond repair, potentially cancerous, or simply no longer needed (e.g., cells between fingers during development).'},

    {id:'b40', topic:'Cell Cycle', diff:'hard',
     q:'What is the role of the p53 protein in the cell cycle?',
     opts:['p53 acts as a tumor suppressor — it detects DNA damage and either halts the cell cycle for repair or triggers apoptosis',
           'p53 promotes rapid cell division by activating growth genes',
           'p53 is an enzyme that replicates DNA during the S phase',
           'p53 forms the spindle fibers that separate chromosomes during mitosis'],
     exp:'p53 is called the "guardian of the genome." When it detects DNA damage, it pauses the cell cycle at the G1 checkpoint to allow repair. If damage is too severe, p53 triggers apoptosis. Mutated p53 is found in ~50% of human cancers.'},

// ── LESSON 3: Why do we have different types of cells? ───────────────────────

    {id:'b41', topic:'Cell Differentiation', diff:'medium',
     q:'Which types of cells primarily undergo mitosis in an adult human?',
     opts:['Somatic (body) cells such as skin, intestinal lining, and blood cells',
           'Neurons (nerve cells) — they divide constantly throughout life',
           'Red blood cells — they divide to replace themselves',
           'Only embryonic cells undergo mitosis; adult cells do not'],
     exp:'Most adult somatic cells can undergo mitosis, especially those that need frequent replacement (skin, gut lining, blood cells). Neurons and muscle cells rarely divide. Red blood cells have no nucleus and cannot divide.'},

    {id:'b42', topic:'Cell Differentiation', diff:'medium',
     q:'Why do skin cells divide much more frequently than liver cells?',
     opts:['Skin cells are continuously shed and need rapid replacement; liver cells are replaced slowly',
           'Skin cells have more DNA, so they replicate faster',
           'Liver cells have lost the ability to divide entirely',
           'Skin cells respond to hormones that speed up mitosis in all cell types'],
     exp:'Different cell types have very different mitotic rates based on their function. Skin and intestinal cells turn over rapidly (days to weeks). Liver cells regenerate on demand. Neurons in the brain rarely divide at all.'},

    {id:'b43', topic:'Cell Differentiation', diff:'easy',
     q:'What is cell differentiation?',
     opts:['The process by which cells with identical DNA develop into specialized cell types with distinct structures and functions',
           'The process of a cell dividing into two identical daughter cells',
           'The mutation of DNA that causes cells to become cancerous',
           'The death of cells that are no longer needed by the body'],
     exp:'All cells in your body have the same DNA, but gene expression differs. Differentiation = cells "switching on" specific genes so a skin cell looks and behaves differently from a neuron or a muscle cell.'},

    {id:'b44', topic:'Stem Cells', diff:'medium',
     q:'What is the role of stem cells in complex organisms?',
     opts:['Stem cells are undifferentiated cells that can divide and develop into specialized cell types to build and maintain tissues',
           'Stem cells are fully differentiated cells that cannot divide further',
           'Stem cells only exist in embryos and disappear after birth',
           'Stem cells are a type of cancer cell that divides without control'],
     exp:'Stem cells are the body\'s "master cells." They self-renew and can differentiate into specialized cells. Embryonic stem cells can become any cell type; adult stem cells (e.g., bone marrow) replace specific tissues throughout life.'},

    {id:'b45', topic:'Stem Cells', diff:'hard',
     q:'Which best describes regeneration as it relates to stem cells?',
     opts:['Regeneration is the ability of some organisms to regrow lost tissues or organs, powered by stem cells that differentiate into needed cell types',
           'Regeneration refers to DNA repair during the S phase of the cell cycle',
           'Regeneration is the process of making copies of a gene in the lab',
           'Regeneration describes when cancer cells revert to normal cell behavior'],
     exp:'Salamanders can regrow limbs; humans regenerate liver tissue — both involve stem cells proliferating and differentiating. The extent of regeneration depends on how many stem cells are available and how they are activated.'},

// ── LESSON 4: How do cells replicate their DNA? ──────────────────────────────

    {id:'b46', topic:'DNA Replication', diff:'easy',
     q:'Which are the four components that make up the structure of a DNA nucleotide?',
     opts:['A phosphate group, deoxyribose sugar, and one of four nitrogenous bases (A, T, G, or C)',
           'A ribose sugar, phosphate group, and one of four bases (A, U, G, or C)',
           'A glucose molecule, amino acid, and a nitrogenous base',
           'A phospholipid, nitrogen base, and a carbohydrate'],
     exp:'DNA nucleotide = phosphate + deoxyribose sugar + nitrogenous base. The four bases: Adenine (A), Thymine (T), Guanine (G), Cytosine (C). RNA uses ribose and Uracil instead of Thymine.'},

    {id:'b47', topic:'DNA Replication', diff:'medium',
     q:'What is the role of helicase in DNA replication?',
     opts:['Helicase unwinds and separates the two strands of the DNA double helix at the replication fork',
           'Helicase adds new complementary nucleotides to the growing DNA strand',
           'Helicase seals the gaps (nicks) between Okazaki fragments on the lagging strand',
           'Helicase synthesizes a short RNA primer to start replication'],
     exp:'Helicase breaks the hydrogen bonds between complementary base pairs, "unzipping" the double helix to expose the template strands. Think of it as a molecular zipper-opener.'},

    {id:'b48', topic:'DNA Replication', diff:'medium',
     q:'What is the role of primase in DNA replication?',
     opts:['Primase synthesizes a short RNA primer that gives DNA polymerase a starting point',
           'Primase unwinds the double helix at the replication fork',
           'Primase connects the sugar-phosphate backbone between Okazaki fragments',
           'Primase proofreads the newly synthesized DNA for errors'],
     exp:'DNA polymerase can only add nucleotides to an existing strand — it cannot start from scratch. Primase lays down a short RNA primer (5–10 nucleotides) that DNA polymerase then extends.'},

    {id:'b49', topic:'DNA Replication', diff:'medium',
     q:'What is the role of DNA polymerase in DNA replication?',
     opts:['DNA polymerase reads the template strand and adds complementary nucleotides to synthesize a new DNA strand in the 5\'→3\' direction',
           'DNA polymerase unzips the double helix by breaking hydrogen bonds',
           'DNA polymerase removes the RNA primers after replication',
           'DNA polymerase joins the two new DNA molecules together after replication'],
     exp:'DNA polymerase is the main replication enzyme — it builds the new strand by adding nucleotides (A with T, G with C) and also proofreads for errors. It can only work 5\'→3\'.'},

    {id:'b50', topic:'DNA Replication', diff:'medium',
     q:'What is the role of DNA ligase in DNA replication?',
     opts:['Ligase joins (seals) the gaps between Okazaki fragments on the lagging strand, completing the new DNA strand',
           'Ligase unwinds the DNA double helix to expose the template strands',
           'Ligase synthesizes the RNA primers used to start DNA synthesis',
           'Ligase adds nucleotides to the leading strand during replication'],
     exp:'The lagging strand is synthesized in fragments (Okazaki fragments). After the RNA primers are removed, ligase acts like molecular glue — sealing the nicks in the sugar-phosphate backbone to create a continuous strand.'},

    {id:'b51', topic:'DNA Replication', diff:'hard',
     q:"What does it mean for DNA strands to be anti-parallel?",
     opts:["The two strands run in opposite directions — one runs 5'→3' and the other runs 3'→5'",
           "The two strands have the same base sequence but different chemical compositions",
           "The two strands separate completely during replication and never rejoin",
           "Anti-parallel means the strands repel each other magnetically"],
     exp:"Each DNA strand has a 5' end (phosphate) and a 3' end (hydroxyl). The two strands are oriented oppositely: if one runs 5'→3' top-to-bottom, the complementary strand runs 3'→5' top-to-bottom. This is why the lagging strand is copied in fragments."},

    {id:'b52', topic:'DNA Replication', diff:'hard',
     q:'What does "semi-conservative replication" mean?',
     opts:['Each new DNA molecule consists of one original (parental) strand and one newly synthesized strand',
           'Only half of the DNA molecule is copied during each round of replication',
           'The original DNA molecule is completely destroyed and two entirely new copies are made',
           'Semi-conservative means replication only happens in the S phase'],
     exp:'Meselson-Stahl (1958) confirmed: after replication, each daughter DNA double helix keeps one original strand paired with one new strand. "Semi" = half old, half new.'},

    {id:'b53', topic:'DNA Replication', diff:'easy',
     q:'What are the base-pairing rules for DNA?',
     opts:['Adenine (A) pairs with Thymine (T); Guanine (G) pairs with Cytosine (C)',
           'Adenine (A) pairs with Guanine (G); Thymine (T) pairs with Cytosine (C)',
           'Adenine (A) pairs with Cytosine (C); Guanine (G) pairs with Thymine (T)',
           'All four bases can pair with any other base'],
     exp:'A–T pairs are held by 2 hydrogen bonds; G–C pairs by 3 hydrogen bonds. This complementary base pairing is what allows accurate DNA replication and RNA synthesis.'},

// ── LESSON 5: What is Central Dogma? ────────────────────────────────────────

    {id:'b54', topic:'Central Dogma', diff:'easy',
     q:'Where does transcription occur in a eukaryotic cell?',
     opts:['In the nucleus, where DNA is located',
           'In the cytoplasm, at the ribosome',
           'In the mitochondria only',
           'In the endoplasmic reticulum'],
     exp:'Transcription happens in the nucleus — RNA polymerase reads the DNA template and produces mRNA. The mRNA then travels to the cytoplasm for translation.'},

    {id:'b55', topic:'Central Dogma', diff:'easy',
     q:'Where does translation occur in a eukaryotic cell?',
     opts:['In the cytoplasm, at ribosomes',
           'In the nucleus, where DNA is located',
           'In the Golgi apparatus',
           'In the smooth endoplasmic reticulum'],
     exp:'Translation occurs at ribosomes in the cytoplasm (or on the rough ER). Ribosomes read the mRNA codons and assemble the amino acid chain (polypeptide).'},

    {id:'b56', topic:'Central Dogma', diff:'medium',
     q:'Which best describes the process of transcription?',
     opts:['RNA polymerase reads a DNA template strand and synthesizes a complementary mRNA strand',
           'Ribosomes read the mRNA and assemble a chain of amino acids',
           'DNA polymerase copies both strands of DNA to produce two identical DNA molecules',
           'tRNA carries amino acids to the ribosome for assembly into proteins'],
     exp:'Transcription: DNA → mRNA. RNA polymerase unwinds the DNA, reads the template 3\'→5\', and builds mRNA 5\'→3\' using complementary base pairing (except U replaces T in RNA).'},

    {id:'b57', topic:'Central Dogma', diff:'medium',
     q:'Which best describes the process of translation?',
     opts:['Ribosomes read mRNA codons and tRNA molecules deliver matching amino acids to build a polypeptide chain',
           'RNA polymerase reads DNA and produces an mRNA copy',
           'DNA is replicated using helicase and DNA polymerase',
           'The polypeptide chain folds into a 3D protein shape'],
     exp:'Translation: mRNA → protein. Ribosome reads each 3-nucleotide codon; tRNA anticodons match and deliver the correct amino acid; the growing polypeptide chain is released at a stop codon.'},

    {id:'b58', topic:'Central Dogma', diff:'hard',
     q:'Using the codon chart: what amino acid does the codon AUG code for?',
     opts:['Methionine (Met) — it is also the universal start codon',
           'Leucine (Leu)',
           'Valine (Val)',
           'It is a stop codon'],
     exp:'AUG codes for methionine AND serves as the universal start codon — every protein begins with AUG. UAA, UAG, and UGA are the three stop codons.'},

    {id:'b59', topic:'Central Dogma', diff:'hard',
     q:'How do amino acid side chains (R groups) determine protein folding?',
     opts:['Interactions between R groups (hydrogen bonds, ionic bonds, hydrophobic interactions) cause the polypeptide to fold into a specific 3D shape',
           'All amino acids have identical R groups, so folding is random',
           'Protein folding is determined only by the DNA sequence, not by amino acids',
           'R groups only affect the color of the protein, not its shape'],
     exp:'Each amino acid has a unique R group that is polar, nonpolar, charged, or hydrophobic. These properties drive folding: hydrophobic R groups cluster inside, charged ones face outward toward water. Shape = function.'},

    {id:'b60', topic:'Central Dogma', diff:'hard',
     q:'Why is correct protein folding essential for function?',
     opts:['The specific 3D shape of a protein determines its active site and ability to interact with other molecules',
           'Protein folding only affects how proteins are transported out of the cell',
           'Misfolded proteins are always repaired automatically by ribosomes',
           'Protein shape has no effect on function — only the amino acid sequence matters'],
     exp:'Protein function depends entirely on shape. Enzymes, antibodies, hormones — all rely on a precise 3D structure to bind their targets. Misfolded proteins can\'t function and may aggregate (as in Alzheimer\'s or Parkinson\'s disease).'},

// ── LESSON 6: How does a mutation lead to a change in protein? ───────────────

    {id:'b61', topic:'Mutations', diff:'easy',
     q:'What is a substitution mutation?',
     opts:['One nucleotide base is replaced by a different base in the DNA sequence',
           'One or more nucleotide bases are added to the DNA sequence',
           'One or more nucleotide bases are removed from the DNA sequence',
           'Two chromosomes exchange segments of DNA'],
     exp:'Substitution (point mutation): one base swaps for another (e.g., A→G). May change an amino acid (missense), create a stop codon (nonsense), or have no effect (silent mutation).'},

    {id:'b62', topic:'Mutations', diff:'medium',
     q:'Why are insertion and deletion mutations often more damaging than substitution mutations?',
     opts:['Insertions and deletions cause a frameshift — all codons downstream are read in the wrong frame, scrambling the entire protein',
           'Insertions and deletions only affect a single amino acid, making the damage minor',
           'Substitutions always create stop codons, which is more harmful',
           'Insertions and deletions only occur in non-coding DNA and have no effect'],
     exp:'Codons are read in groups of 3. Adding or removing a base shifts the reading frame for every codon that follows — like removing a letter from a sentence and re-reading: "THE CAT SAT" → "TEC ATS AT." The entire protein downstream is scrambled.'},

    {id:'b63', topic:'Mutations', diff:'medium',
     q:'How does a mutation in DNA lead to a change in protein structure?',
     opts:['A changed DNA sequence → different mRNA codon during transcription → different amino acid delivered during translation → altered polypeptide that may fold differently',
           'A mutation directly changes the shape of a finished protein without affecting the DNA',
           'Mutations only affect DNA replication, not protein synthesis',
           'A mutation changes the ribosome, not the mRNA or amino acid sequence'],
     exp:'The pathway: mutated DNA → altered mRNA codon (transcription) → wrong amino acid inserted (translation) → polypeptide with changed R groups → different folding → altered or lost function.'},

    {id:'b64', topic:'Mutations', diff:'hard',
     q:'What happens to the cell cycle if the p53 gene is mutated?',
     opts:['The G1 checkpoint fails — cells with damaged DNA bypass quality control and continue dividing, accumulating more mutations',
           'The cell cycle speeds up temporarily, then returns to normal',
           'The cell immediately undergoes apoptosis when p53 is mutated',
           'Mutated p53 causes cells to stop dividing permanently'],
     exp:'Normally p53 halts the cycle at G1 to allow DNA repair, or triggers apoptosis if damage is irreparable. A mutated p53 protein cannot bind DNA or activate these pathways — damaged cells keep dividing, which is a hallmark of cancer.'},

    {id:'b65', topic:'Mutations', diff:'hard',
     q:'How can a single nucleotide substitution in a gene lead to a completely non-functional protein?',
     opts:['The substitution may create a premature stop codon, producing a truncated protein that cannot fold or function correctly',
           'A single substitution never affects protein function — only large deletions do',
           'The substitution changes only the DNA, not the mRNA, so the protein is unaffected',
           'Ribosomes detect single-base substitutions and correct them before translation'],
     exp:'A nonsense mutation (substitution creating a stop codon — e.g., UAU→UAA) truncates the polypeptide chain prematurely. The short, misfolded fragment almost always loses function. Sickle cell disease is a missense example: one A→T substitution changes Glu→Val in hemoglobin.'},

// ── LESSON 7: How do external factors lead to cancer? ────────────────────────

    {id:'b66', topic:'Cancer Biology', diff:'easy',
     q:'What is a mutagen?',
     opts:['Any physical, chemical, or biological agent that increases the rate of mutations in DNA',
           'A protein that repairs DNA damage caused by radiation',
           'A type of cell that destroys cancer cells in the immune system',
           'An enzyme that corrects errors during DNA replication'],
     exp:'Mutagens cause DNA mutations that can potentially lead to cancer. Examples: UV radiation (melanoma), tobacco smoke (lung cancer), certain chemicals, and some viruses (HPV → cervical cancer).'},

    {id:'b67', topic:'Cancer Biology', diff:'medium',
     q:'How can UV radiation from the sun cause skin cancer?',
     opts:['UV radiation causes thymine dimers — covalent bonds between adjacent thymine bases — that distort the DNA and can cause mutations if not repaired',
           'UV radiation directly destroys cancer cells, but also damages healthy cells',
           'UV radiation inserts extra nucleotides into the DNA, causing frameshift mutations',
           'UV radiation only damages the cell membrane, not the DNA itself'],
     exp:'UV-B radiation causes adjacent thymine bases to bond together (thymine dimers), distorting the DNA. Normally repaired by nucleotide excision repair — but if mutations accumulate in genes like p53, skin cancer can develop.'},

    {id:'b68', topic:'Cancer Biology', diff:'medium',
     q:'Which of the following is the best example of a chemical mutagen?',
     opts:['The carcinogens in tobacco smoke, which bind to DNA and cause base substitutions',
           'Visible light from a lamp',
           'Cold temperatures that slow cell division',
           'Increased oxygen levels in the blood'],
     exp:'Tobacco smoke contains polycyclic aromatic hydrocarbons (PAHs) and other chemicals that bind to DNA bases, causing substitution mutations. This is why smoking dramatically increases the risk of lung, throat, and many other cancers.'},

    {id:'b69', topic:'Cancer Biology', diff:'hard',
     q:'Why does it usually take multiple mutations — not just one — for a normal cell to become cancerous?',
     opts:['Cancer requires mutations in multiple control systems simultaneously: cell cycle checkpoints, apoptosis pathways, growth factor signaling, and DNA repair genes',
           'One mutation is always sufficient to cause cancer if it occurs in p53',
           'The immune system prevents the first mutation from having any effect',
           'Multiple mutations are needed only for blood cancers, not solid tumors'],
     exp:'Cancer is a multi-step process. A cell needs to: bypass checkpoints, disable apoptosis, ignore "stop dividing" signals, activate growth genes, and eventually invade other tissues. Each step requires a separate mutation — which is why cancer risk increases with age (more time for mutations to accumulate).'},

  ],

  english: [
    {id:'e1', topic:'Literary Devices', diff:'easy',
     q:"'The wind whispered through the trees' is an example of:",
     opts:['Personification','Simile','Metaphor','Alliteration'],
     exp:'Personification gives human qualities (whispering) to a non-human subject (wind).'},
    {id:'e2', topic:'Literary Devices', diff:'easy',
     q:'A simile uses which words to compare two unlike things?',
     opts:['"Like" or "as"','"Is" or "are"','"Was" or "were"','"And" or "but"'],
     exp:'Similes use "like" or "as": "brave as a lion," "she ran like the wind."'},
    {id:'e3', topic:'Literary Devices', diff:'easy',
     q:'"Peter Piper picked a peck of pickled peppers" demonstrates:',
     opts:['Alliteration','Assonance','Consonance','Onomatopoeia'],
     exp:'Alliteration is the repetition of an initial consonant sound (P) in connected words.'},
    {id:'e4', topic:'Literary Devices', diff:'medium',
     q:'Dramatic irony occurs when:',
     opts:['The audience knows something characters don\'t','A character says the opposite of what they mean','Events turn out opposite to expectations','Two characters misunderstand each other'],
     exp:'Dramatic irony creates tension — readers know something the character does not (e.g., Romeo thinks Juliet is dead).'},
    {id:'e5', topic:'Literary Devices', diff:'medium',
     q:'An allusion is a reference to:',
     opts:['Another work, event, or person','A made-up fictional story','The author\'s personal life','A character\'s dream'],
     exp:'Allusions reference history, mythology, literature, or culture. "He was a real Romeo" alludes to Shakespeare.'},
    {id:'e6', topic:'Literary Devices', diff:'easy',
     q:'Onomatopoeia refers to words that:',
     opts:['Imitate the sounds they describe','Contradict their meaning','Repeat consonant sounds','Compare unlike things'],
     exp:'Examples: buzz, crash, sizzle, hiss — the word sound mimics what it describes.'},
    {id:'e7', topic:'Literary Devices', diff:'hard',
     q:'Anaphora is the device of:',
     opts:['Repeating words at the START of successive clauses','Repeating words at the END of successive clauses','Interrupting a sentence mid-thought','Addressing an absent person'],
     exp:'MLK\'s "I have a dream…" repeated at clause starts is classic anaphora.'},
    {id:'e8', topic:'Literary Analysis', diff:'easy',
     q:"A story's theme is best described as:",
     opts:['The central message about human experience','The main character\'s personality','The sequence of events','The setting'],
     exp:'Theme is a universal idea — love, justice, identity — not the plot itself.'},
    {id:'e9', topic:'Literary Analysis', diff:'medium',
     q:'A foil character serves to:',
     opts:['Contrast another character to highlight their traits','Support the antagonist','Narrate from outside the story','Represent a symbolic idea'],
     exp:"A foil's contrasting qualities sharpen our understanding of another character (e.g., Laertes foils Hamlet)."},
    {id:'e10', topic:'Literary Analysis', diff:'easy',
     q:'The climax of a narrative is:',
     opts:['The moment of highest tension or turning point','The opening that establishes setting','The resolution of conflicts','The introduction of the antagonist'],
     exp:'The climax is the crisis point — after which action falls toward resolution.'},
    {id:'e11', topic:'Literary Analysis', diff:'hard',
     q:'A bildungsroman is a novel that:',
     opts:["Follows a character's moral and psychological growth",'Portrays a historical event','Features a tragic hero\'s downfall','Is written in stream-of-consciousness'],
     exp:'"The Catcher in the Rye," "Great Expectations." German term means "formation novel."'},
    {id:'e12', topic:'Shakespeare', diff:'easy',
     q:'A Shakespearean sonnet has how many lines?',
     opts:['14','12','16','10'],
     exp:'All sonnets have 14 lines. Shakespearean: three quatrains + a couplet.'},
    {id:'e13', topic:'Shakespeare', diff:'medium',
     q:'Iambic pentameter has how many syllables per line?',
     opts:['10','8','12','14'],
     exp:'Iambic pentameter = 5 iambs × 2 syllables = 10. "Shall I comPARE thee TO a SUMmer\'s DAY?"'},
    {id:'e14', topic:'Grammar', diff:'medium',
     q:'Which sentence is grammatically correct?',
     opts:['She and I went to the store.','Me and her went to the store.','Her and me went to the store.','I and her went to the store.'],
     exp:'Use subject pronouns as subjects. Test by removing one: "I went" ✓; "me went" ✗.'},
    {id:'e15', topic:'Grammar', diff:'medium',
     q:'A clause that cannot stand alone as a sentence is called:',
     opts:['Dependent (subordinate) clause','Independent clause','Compound sentence','Appositive phrase'],
     exp:'Dependent clauses begin with subordinating conjunctions (because, although, when) and cannot stand alone.'},
    {id:'e16', topic:'Vocabulary', diff:'medium',
     q:'The word "ephemeral" means:',
     opts:['Lasting for a very short time','Lasting forever','Difficult to understand','Full of energy'],
     exp:'From Greek ephemeros ("daily"): lasting only a day or short time. "The ephemeral beauty of cherry blossoms."'},
    {id:'e17', topic:'Vocabulary', diff:'medium',
     q:'The word "ambivalent" means:',
     opts:['Having mixed or contradictory feelings','Feeling very strongly positive','Completely indifferent','Extremely energetic'],
     exp:'"Ambivalent" (ambi- = both) describes simultaneously holding opposing feelings.'},
    {id:'e18', topic:'Vocabulary', diff:'hard',
     q:'The word "ubiquitous" means:',
     opts:['Present or found everywhere','Rare and hard to find','Morally questionable','Extremely large'],
     exp:'Smartphones are ubiquitous. From Latin ubique meaning "everywhere."'},
    {id:'e19', topic:'Argument & Rhetoric', diff:'medium',
     q:'Logos is an appeal to:',
     opts:['Logic and reason','Emotions and feelings','The speaker\'s credibility','Self-interest'],
     exp:"Aristotle's three modes: Logos (logic), Pathos (emotion), Ethos (credibility)."},
    {id:'e20', topic:'Argument & Rhetoric', diff:'easy',
     q:'A thesis statement:',
     opts:['States the main argument and indicates the essay\'s direction','Summarizes what the essay already proved','Introduces background only','Quotes a famous author'],
     exp:'A strong thesis is arguable, specific, and tells the reader what to expect.'},
    {id:'e21', topic:'Literary Devices', diff:'hard',
     q:'An extended metaphor:',
     opts:['Sustains a comparison throughout an entire work or long passage','Uses "like" or "as" to compare','Compares using the word "is"','Gives human traits to an object'],
     exp:'When a metaphor is developed across many lines or an entire text, it\'s called a conceit or extended metaphor.'},
    {id:'e22', topic:'Literary Analysis', diff:'easy',
     q:'First-person point of view is identified by the use of:',
     opts:['I, me, my, we, our','He, she, it, they','You, your','One, one\'s'],
     exp:'First-person narration uses "I" and creates intimacy, limiting perspective to the narrator.'},
    {id:'e23', topic:'Shakespeare', diff:'hard',
     q:'The tragic flaw (hamartia) of a tragic hero is:',
     opts:['An error or weakness that leads to their downfall','An act of random fate','A villain\'s interference','The hero\'s refusal to act'],
     exp:'Hamartia (Aristotle): the hero\'s own flaw — hubris, jealousy, ambition — causes their ruin.'},
    {id:'e24', topic:'Poetry', diff:'easy',
     q:'Which poetic form does NOT require rhyme or specific meter?',
     opts:['Free verse','Sonnet','Haiku','Limerick'],
     exp:'Free verse has no set rhyme scheme or meter. Walt Whitman\'s "Leaves of Grass" is a famous example.'},
    {id:'e25', topic:'Literary Analysis', diff:'medium',
     q:'When a character speaks their thoughts aloud, alone on stage, it is called a:',
     opts:['Soliloquy','Monologue','Aside','Dialogue'],
     exp:'A soliloquy (e.g., Hamlet\'s "To be or not to be") reveals inner thoughts when alone.'},
    {id:'e26', topic:'Grammar', diff:'medium',
     q:'Which punctuation mark correctly joins two independent clauses without a conjunction?',
     opts:['Semicolon (;)','Comma (,)','Colon (:)','Em dash (—)'],
     exp:'A semicolon joins independent clauses: "I studied hard; I aced the test." A comma alone = comma splice.'},
    {id:'e27', topic:'Vocabulary', diff:'hard',
     q:'The word "recalcitrant" most nearly means:',
     opts:['Stubbornly resistant to authority','Easily persuaded','Deeply sorrowful','Extremely knowledgeable'],
     exp:'A recalcitrant student refuses to follow directions. From Latin recalcitrare — "to kick back."'},
    {id:'e28', topic:'Literary Devices', diff:'medium',
     q:'Juxtaposition is the technique of:',
     opts:['Placing contrasting ideas side by side','Repeating a sound for effect','Referring to historical events','Giving human qualities to objects'],
     exp:'Dickens: "It was the best of times, it was the worst of times." Classic juxtaposition.'},
    {id:'e29', topic:'Literary Analysis', diff:'easy',
     q:'The exposition of a story establishes:',
     opts:['Setting, characters, and background information','The climax of the conflict','The story\'s resolution','The turning point of the plot'],
     exp:'Exposition introduces the world, key characters, and initial situation before conflict begins.'},
    {id:'e30', topic:'Literary Devices', diff:'medium',
     q:'Hyperbole is best defined as:',
     opts:['Extreme exaggeration for effect','Understatement to downplay meaning','A comparison using "like" or "as"','Repeating initial consonant sounds'],
     exp:'"I\'m so hungry I could eat a horse" is hyperbole — the exaggeration makes the point memorable.'},
  ],

  apCSP: [
    {id:'c1', topic:'Binary & Data', diff:'medium',
     q:'What is the decimal value of binary 1010?',
     opts:['10','5','12','8'],
     exp:'1010 = 1×8+0×4+1×2+0×1 = 10.'},
    {id:'c2', topic:'Binary & Data', diff:'easy',
     q:'How many bits are in one byte?',
     opts:['8','4','16','2'],
     exp:'1 byte = 8 bits. A byte can represent 2⁸ = 256 different values.'},
    {id:'c3', topic:'Binary & Data', diff:'easy',
     q:'Which color model do computer monitors use?',
     opts:['RGB (Red, Green, Blue)','CMYK','HSL','YUV'],
     exp:'Monitors use additive color mixing with RGB. Printers use subtractive CMYK.'},
    {id:'c4', topic:'Algorithms', diff:'easy',
     q:'An algorithm is best defined as:',
     opts:['A finite, step-by-step set of instructions to solve a problem','A programming language','A type of computer hardware','A function in Python'],
     exp:'Algorithms are language-independent problem-solving procedures. Must be finite, unambiguous, effective.'},
    {id:'c5', topic:'Algorithms', diff:'medium',
     q:'Which search algorithm has O(log n) time complexity?',
     opts:['Binary search','Linear search','Bubble sort','Selection sort'],
     exp:'Binary search halves the search space each step → O(log n). Requires a sorted list.'},
    {id:'c6', topic:'Algorithms', diff:'easy',
     q:'An algorithm that never terminates due to a repeated condition is called:',
     opts:['An infinite loop','A recursive function','A dead loop','An overflow'],
     exp:'Infinite loops occur when the exit condition is never reached (e.g., while True: with no break).'},
    {id:'c7', topic:'Programming', diff:'easy',
     q:'In most programming languages, a Boolean can only hold:',
     opts:['True or False','0, 1, or 2','Yes, No, or Maybe','Any integer'],
     exp:'Boolean has exactly two values: True (1) and False (0). Named after mathematician George Boole.'},
    {id:'c8', topic:'Programming', diff:'easy',
     q:'What is the term for a named storage location that holds a value?',
     opts:['Variable','Function','Loop','Parameter'],
     exp:'A variable is a named reference to a memory location storing a value that can change.'},
    {id:'c9', topic:'Programming', diff:'medium',
     q:"A function's parameter is:",
     opts:['A variable that receives values passed into the function','The value a function returns','A comment describing the function','The function\'s name'],
     exp:'Parameters (formal) are placeholders in the definition. Arguments are the actual values passed in.'},
    {id:'c10', topic:'Abstraction', diff:'medium',
     q:'Abstraction in computing refers to:',
     opts:['Hiding complexity while exposing only essential features','Converting code to machine language','Searching for patterns in data','Encrypting data'],
     exp:'Abstraction: use a car without understanding the engine, or call a function without knowing its internals.'},
    {id:'c11', topic:'Data & Analysis', diff:'medium',
     q:'Metadata is best described as:',
     opts:['Data that describes other data','The largest dataset in a collection','Encrypted personal information','A type of programming error'],
     exp:"An image's metadata includes file size, creation date, GPS, camera settings — data ABOUT the data."},
    {id:'c12', topic:'Data & Analysis', diff:'medium',
     q:'Lossless compression:',
     opts:['Perfectly reconstructs the original data after decompression','Discards some data for higher compression','Encrypts data before storage','Only compresses text files'],
     exp:'Lossless (ZIP, PNG): original perfectly recoverable. Lossy (JPEG, MP3): some data permanently lost.'},
    {id:'c13', topic:'Internet & Networks', diff:'easy',
     q:'HTTP stands for:',
     opts:['HyperText Transfer Protocol','High-Traffic Transfer Process','HyperText Transport Program','Host Transfer Protocol'],
     exp:'HTTP is the protocol for transmitting web pages. HTTPS adds TLS encryption.'},
    {id:'c14', topic:'Internet & Networks', diff:'medium',
     q:'DNS (Domain Name System) translates:',
     opts:['Domain names to IP addresses','IP addresses to physical locations','URLs into HTML','Packets into data streams'],
     exp:"DNS is the internet's phone book — converts 'google.com' into a numeric IP like 142.250.80.46."},
    {id:'c15', topic:'Internet & Networks', diff:'hard',
     q:"The Internet's packet-switching model means:",
     opts:['Data is broken into packets routed independently and reassembled','All data takes one fixed path','Data is sent as one continuous stream','Only approved devices can send data'],
     exp:'Packet switching routes packets dynamically, making the internet resilient and scalable.'},
    {id:'c16', topic:'Cybersecurity', diff:'easy',
     q:'A phishing attack involves:',
     opts:['Tricking users into revealing sensitive information via fake messages','Breaking encryption by brute force','Flooding a server with traffic','Exploiting a software vulnerability'],
     exp:'Phishing uses deceptive emails/websites impersonating trusted sources to steal credentials.'},
    {id:'c17', topic:'Cybersecurity', diff:'easy',
     q:'Encryption converts data into a coded form to:',
     opts:['Prevent unauthorized access','Speed up data transmission','Compress file sizes','Detect software bugs'],
     exp:'Encryption (AES, RSA) ensures intercepted data cannot be read without the decryption key.'},
    {id:'c18', topic:'Cybersecurity', diff:'easy',
     q:'A strong password should include:',
     opts:['Uppercase, lowercase, numbers, and symbols','Only lowercase letters','Your name and birth year','A single dictionary word'],
     exp:'Password complexity and length dramatically increase time needed for brute-force attacks.'},
    {id:'c19', topic:'Global Impact', diff:'medium',
     q:'The digital divide refers to:',
     opts:['The gap between those with and without technology access','The difference between analog and digital signals','A split in programming language communities','Separation of hardware and software'],
     exp:'The digital divide affects access to education, economic opportunities, and civic participation.'},
    {id:'c20', topic:'Global Impact', diff:'medium',
     q:'Crowdsourcing uses:',
     opts:['Input from large online groups to solve problems or gather data','Specialized AI to analyze data','Corporate teams to develop products','Cloud servers to store information'],
     exp:'Wikipedia, reCAPTCHA, and citizen science projects use crowdsourcing — distributed human input.'},
    {id:'c21', topic:'Global Impact', diff:'medium',
     q:"Moore's Law (1965) states that:",
     opts:["Transistor counts on chips double roughly every two years",'Internet speed doubles every year','Storage costs double every five years','Software complexity doubles each decade'],
     exp:"Moore's Law has driven exponential computing growth for decades, though it's now slowing."},
    {id:'c22', topic:'Creative Development', diff:'easy',
     q:'Open-source software is software whose:',
     opts:['Source code is publicly available for anyone to view and modify','Code is free but cannot be modified','Use requires a commercial license','Source code is kept secret'],
     exp:'Open source (Linux, Firefox, Python) allows community collaboration and freely shared improvements.'},
    {id:'c23', topic:'Data & Analysis', diff:'easy',
     q:'Which is an example of a data visualization tool?',
     opts:['A bar chart showing trends over time','A for-loop iterating through data','An if-else conditional','A binary search algorithm'],
     exp:'Data visualizations (charts, graphs, heat maps) transform raw numbers into visible patterns.'},
    {id:'c24', topic:'Algorithms', diff:'hard',
     q:'A heuristic algorithm:',
     opts:["Provides a 'good enough' solution quickly, not guaranteed optimal",'Always finds the perfect solution','Only works on sorted data','Requires artificial intelligence'],
     exp:'GPS navigation uses heuristics — finds a very good route fast rather than checking every possible path.'},
    {id:'c25', topic:'Internet & Networks', diff:'medium',
     q:'The World Wide Web (WWW) is:',
     opts:['A system of interlinked hypertext documents accessed via the internet','The same thing as the internet','A private government network','A type of wireless network'],
     exp:"The internet is the infrastructure. The Web (Tim Berners-Lee, 1989) is a service running ON the internet."},
    {id:'c26', topic:'Programming', diff:'easy',
     q:'What does a conditional (if/else) statement control?',
     opts:['Which code block runs based on a condition being true or false','How many times a loop repeats','The order of function definitions','How variables are named'],
     exp:"Conditionals direct program flow: 'if it's raining, take umbrella; else, wear sunglasses.'"},
    {id:'c27', topic:'Abstraction', diff:'medium',
     q:'Which is the BEST example of procedural abstraction?',
     opts:["Calling a sort() function without knowing its internal code",'Writing a loop that counts to 100','Naming a variable x','Using an if-else statement'],
     exp:'Procedural abstraction: call a procedure and use its result without knowing its internal workings.'},
    {id:'c28', topic:'Cybersecurity', diff:'medium',
     q:'Two-factor authentication (2FA) improves security because:',
     opts:['It requires two separate verification steps even if a password is stolen','It doubles password length','It encrypts all network traffic','It prevents phishing emails'],
     exp:'2FA combines something you KNOW (password) + HAVE (phone) or ARE (fingerprint).'},
    {id:'c29', topic:'Binary & Data', diff:'hard',
     q:'Convert decimal 13 to binary.',
     opts:['1101','1011','1110','1001'],
     exp:'13 = 8+4+1 = 2³+2²+2⁰ → 1101.'},
    {id:'c30', topic:'Global Impact', diff:'medium',
     q:'A Creative Commons license allows creators to:',
     opts:['Share their work with specified permissions','Prevent all use of their work','Sell exclusively','Remove all copyright'],
     exp:'CC licenses specify what others can do: share, modify, use commercially, etc.'},
  ],

  spanish2: [
    {id:'s1', topic:'Preterite Tense', diff:'easy',
     q:"What is the preterite (yo) form of 'hablar'?",
     opts:['Hablé','Hablaba','Hablo','Hablaré'],
     exp:'Preterite -ar endings (yo): -é. Note the accent mark.'},
    {id:'s2', topic:'Ser vs. Estar', diff:'medium',
     q:"Which verb would you use to describe someone's nationality?",
     opts:['Ser (permanent characteristic)','Estar (temporary state)','Tener (to have)','Ir (to go)'],
     exp:'Use SER for origin, nationality, identity. ESTAR for location, temporary states, feelings.'},
    {id:'s3', topic:'Present Tense', diff:'medium',
     q:"What does 'gustar' literally mean?",
     opts:['To be pleasing to','To like','To enjoy','To love'],
     exp:'"Me gusta el libro" literally means "the book is pleasing to me." Subject = the thing liked.'},
    {id:'s4', topic:'Present Tense', diff:'medium',
     q:"Correct conjugation of 'poder' (to be able) for 'yo'?",
     opts:['Puedo','Pode','Podeo','Puede'],
     exp:'Poder is o→ue stem-changing: puedo, puedes, puede, podemos, podéis, pueden.'},
    {id:'s5', topic:'Reflexive Verbs', diff:'medium',
     q:'What is a reflexive verb?',
     opts:['A verb where the subject performs the action on themselves','A verb with two objects','A verb that is always irregular','A verb used only in the past tense'],
     exp:'Reflexive pronouns: me, te, se, nos, os, se. "Me lavo las manos" = I wash my hands.'},
    {id:'s6', topic:'Preterite Tense', diff:'medium',
     q:"The preterite forms of 'ser' and 'ir' are identical. What is the preterite (yo) form?",
     opts:['Fui','Era','Soy','Voy'],
     exp:'Ser and ir share preterite forms: fui, fuiste, fue, fuimos, fuisteis, fueron.'},
    {id:'s7', topic:'Imperfect Tense', diff:'medium',
     q:'How do you form the imperfect (yo) of regular -ar verbs?',
     opts:['-aba','-ía','-é','-aba or -ía'],
     exp:'-AR imperfect: -aba, -abas, -aba, -ábamos, -abais, -aban.'},
    {id:'s8', topic:'Imperfect Tense', diff:'hard',
     q:'When would you use the IMPERFECT rather than the preterite?',
     opts:['To describe ongoing past states or habitual past actions','To describe a single completed past event','To talk about future plans','To give commands'],
     exp:'Imperfect = background, habits ("used to"): "De niño, jugaba fútbol." Preterite = specific events.'},
    {id:'s9', topic:'Object Pronouns', diff:'medium',
     q:"What is the direct object pronoun for 'him' in Spanish?",
     opts:['Lo','Le','Se','La'],
     exp:'Direct object pronouns: me, te, lo/la, nos, os, los/las. "Lo veo" = I see him.'},
    {id:'s10', topic:'Object Pronouns', diff:'medium',
     q:"The indirect object pronoun meaning 'to her / for her' is:",
     opts:['Le','La','Se','Lo'],
     exp:'Indirect object pronouns (to/for whom): me, te, le, nos, os, les.'},
    {id:'s11', topic:'Vocabulary', diff:'easy',
     q:"What does '¿Mucho gusto?' mean?",
     opts:['Nice to meet you','How much does it cost?','You\'re welcome','Do you like it?'],
     exp:'Used when meeting someone for the first time. Response: "Igualmente" (likewise).'},
    {id:'s12', topic:'Vocabulary', diff:'easy',
     q:"What does 'hay' mean?",
     opts:['There is / there are','Today','Yesterday','Never'],
     exp:'"Hay" is the impersonal form of "haber." Invariable: "Hay un libro." / "Hay tres libros."'},
    {id:'s13', topic:'Vocabulary', diff:'medium',
     q:"What does 'sin embargo' mean?",
     opts:['However / nevertheless','Without a doubt','On the other hand','In addition'],
     exp:'"Sin embargo" means "however" or "nevertheless." Useful transition word for essays.'},
    {id:'s14', topic:'Vocabulary', diff:'hard',
     q:"'Acabar de' + infinitive means:",
     opts:['To have just done something','To finish doing something','To stop doing something','To begin to do something'],
     exp:'"Acabo de comer" = I have just eaten. Always uses present or imperfect of "acabar."'},
    {id:'s15', topic:'Present Tense', diff:'easy',
     q:"Translate: 'Me llamo Alejandro.'",
     opts:['My name is Alejandro','I call Alejandro','They call me Alejandro','Alejandro is calling me'],
     exp:'"Llamarse" is reflexive. "Me llamo" literally = "I call myself." Standard self-introduction.'},
    {id:'s16', topic:'Vocabulary', diff:'easy',
     q:"What does 'también' mean?",
     opts:['Also / too','Neither','But','Or'],
     exp:'"También" means "also/too." Negative counterpart: "tampoco" (neither/not either).'},
    {id:'s17', topic:'Vocabulary', diff:'easy',
     q:"What does 'hace frío' mean?",
     opts:['It is cold','It is hot','It is windy','It is raining'],
     exp:'Weather uses "hacer": hace frío, hace calor, hace sol, hace viento.'},
    {id:'s18', topic:'Present Tense', diff:'medium',
     q:"'Dormir' is which type of stem-changing verb?",
     opts:['o → ue (duermo, duermes...)','e → ie','e → i','No stem change'],
     exp:'Dormir: duermo, duermes, duerme, dormimos, dormís, duermen.'},
    {id:'s19', topic:'Subjunctive Intro', diff:'hard',
     q:'The subjunctive mood is typically used to express:',
     opts:['Doubt, wishes, emotions, and recommendations','Facts and certainties','Commands to "tú"','Future events that are certain'],
     exp:'WEIRDO triggers subjunctive: Wishes, Emotion, Impersonal expressions, Recommendations, Doubt, Ojalá.'},
    {id:'s20', topic:'Vocabulary', diff:'hard',
     q:"'Ojalá' is used in Spanish to express:",
     opts:['Hope or wish (hopefully / I hope that)','Surprise','Certainty','Contradiction'],
     exp:'"Ojalá" derives from Arabic "Inshallah." Triggers subjunctive: "Ojalá que llueva café."'},
    {id:'s21', topic:'Present Tense', diff:'easy',
     q:"What does 'tener' mean, and how do you conjugate it for 'yo'?",
     opts:['To have; tengo','To be; soy','To want; quero','To go; voy'],
     exp:'"Tener" = to have. Yo tengo (irregular). Also: tener hambre, tener razón, tener que + inf.'},
    {id:'s22', topic:'Vocabulary', diff:'medium',
     q:"In which Spanish-speaking country is 'vosotros' commonly used?",
     opts:['Spain','Mexico','Argentina','Colombia'],
     exp:'"Vosotros" is the informal "you all" used in Spain. Latin America uses "ustedes" for both formal and informal plural.'},
    {id:'s23', topic:'Preterite Tense', diff:'hard',
     q:"Which preterite verb form is highly irregular?",
     opts:['Tuve (I had) — from tener','Comí (I ate) — from comer','Hablé (I spoke) — from hablar','Viví (I lived) — from vivir'],
     exp:'Tener in preterite: tuve, tuviste, tuvo, tuvimos, tuvisteis, tuvieron. No accent marks!'},
    {id:'s24', topic:'Object Pronouns', diff:'hard',
     q:'When using both direct and indirect object pronouns together, which order is correct?',
     opts:['Indirect then direct (le lo → se lo)','Direct then indirect','Either order','Only one pronoun can be used'],
     exp:'Spanish: indirect before direct. When both begin with "l," indirect becomes "se": "Se lo doy."'},
    {id:'s25', topic:'Present Tense', diff:'hard',
     q:"Translate: '¿Cuánto tiempo llevas estudiando español?'",
     opts:['How long have you been studying Spanish?','How much Spanish time do you have?','When did you start studying Spanish?','Do you study Spanish for a long time?'],
     exp:'"Llevar + gerund" expresses duration of ongoing action. "Llevo tres años estudiando" = I\'ve been studying 3 years.'},
    {id:'s26', topic:'Imperfect Tense', diff:'hard',
     q:'Which verb is irregular in the imperfect tense?',
     opts:['Ir (iba, ibas, iba...)','Hablar (hablaba)','Comer (comía)','Vivir (vivía)'],
     exp:'Only 3 verbs are irregular in the imperfect: ir (iba), ser (era), ver (veía).'},
    {id:'s27', topic:'Vocabulary', diff:'easy',
     q:"What does 'a veces' mean?",
     opts:['Sometimes','Always','Never','Often'],
     exp:'Frequency: siempre (always), a veces (sometimes), nunca (never), a menudo (often).'},
    {id:'s28', topic:'Reflexive Verbs', diff:'medium',
     q:"Choose the correct reflexive pronoun: 'Ella ___ despertó a las seis.'",
     opts:['se','me','te','nos'],
     exp:'Reflexive pronouns agree with subject. Ella → se. "Ella se despertó" = She woke herself up.'},
    {id:'s29', topic:'Ser vs. Estar', diff:'medium',
     q:"Which sentence correctly uses 'estar'?",
     opts:['Estoy cansado hoy.','Soy cansado.','Es de España.','Son hermanos.'],
     exp:'ESTAR for temporary states: "Estoy cansado" (I am tired right now).'},
    {id:'s30', topic:'Vocabulary', diff:'easy',
     q:"Translate: 'Tengo que estudiar para el examen.'",
     opts:['I have to study for the exam.','I want to study for the exam.','I should study for the exam.','I am going to study for the exam.'],
     exp:'"Tener que + infinitive" = to have to (obligation). "Ir a + inf" = going to. "Deber" = should.'},
  ],
};

const RESOURCES = [
  // Algebra 2
  {subject:'algebra2', title:'Khan Academy – Algebra 2', desc:'Full course: functions, polynomials, exponentials, logs, conics, stats.', url:'https://www.khanacademy.org/math/algebra2', icon:'🎓', featured:true},
  {subject:'algebra2', title:'Desmos Graphing Calculator', desc:'Free, powerful graphing tool. Perfect for visualizing functions and conics.', url:'https://www.desmos.com/calculator', icon:'📈', featured:true},
  {subject:'algebra2', title:'Khan Academy – Logarithms', desc:'Deep-dive into log properties, change of base, and solving log equations.', url:'https://www.khanacademy.org/math/algebra2/x2ec2f6f830c9fb89:log', icon:'📘'},
  {subject:'algebra2', title:'IXL – Algebra 2 Practice', desc:'Thousands of adaptive practice problems organized by skill level.', url:'https://www.ixl.com/math/algebra-2', icon:'✏️'},
  {subject:'algebra2', title:'Mathway – Problem Solver', desc:'Step-by-step algebra solver — enter any equation and see the full solution.', url:'https://www.mathway.com/algebra', icon:'✅'},
  {subject:'algebra2', title:'PurpleMath – Algebra Lessons', desc:'Clear written explanations of every Algebra 2 topic.', url:'https://www.purplemath.com/modules/index.htm', icon:'📖'},
  // Biology
  {subject:'biology', title:'Khan Academy – AP Biology', desc:'Complete AP Biology course covering all major units.', url:'https://www.khanacademy.org/science/ap-biology', icon:'🎓', featured:true},
  {subject:'biology', title:'HHMI BioInteractive', desc:'Free, research-based biology videos and animations from top scientists.', url:'https://www.biointeractive.org', icon:'▶️', featured:true},
  {subject:'biology', title:'CrashCourse Biology', desc:'Engaging 10–15 min YouTube videos covering all major biology topics.', url:'https://www.youtube.com/playlist?list=PL3EED4C1D684D3ADF', icon:'📺'},
  {subject:'biology', title:'Bozeman Science', desc:'Detailed AP Biology topic videos by an award-winning AP teacher.', url:'https://www.bozemanscience.com/ap-biology', icon:'🎬'},
  {subject:'biology', title:'Quizlet – Biology Flashcards', desc:'Pre-made biology flashcard sets matching your textbook.', url:'https://quizlet.com/subject/biology', icon:'🃏'},
  // English
  {subject:'english', title:'Khan Academy – Grammar', desc:'Parts of speech, punctuation, sentence structure, and style — with practice.', url:'https://www.khanacademy.org/humanities/grammar', icon:'🎓', featured:true},
  {subject:'english', title:'NoRedInk – Grammar Practice', desc:'Adaptive grammar and writing exercises used by schools nationwide.', url:'https://www.noredink.com', icon:'✏️', featured:true},
  {subject:'english', title:'Vocabulary.com', desc:'Learn vocabulary in context with definitions, examples, and games.', url:'https://www.vocabulary.com', icon:'📝'},
  {subject:'english', title:'SparkNotes – Literature Guides', desc:'Study guides and analysis for Romeo & Juliet and all major texts.', url:'https://www.sparknotes.com', icon:'📚'},
  {subject:'english', title:'Purdue OWL – Writing Lab', desc:'Authoritative writing guides: MLA format, essay structure, citations.', url:'https://owl.purdue.edu/owl/general_writing', icon:'🦉'},
  {subject:'english', title:'LitCharts – Literary Analysis', desc:'Color-coded, theme-by-theme literary analysis for hundreds of texts.', url:'https://www.litcharts.com', icon:'🎨'},
  // AP CSP
  {subject:'apCSP', title:'Khan Academy – AP CSP', desc:'Official AP CSP curriculum: algorithms, programming, data, and internet.', url:'https://www.khanacademy.org/computing/ap-computer-science-principles', icon:'🎓', featured:true},
  {subject:'apCSP', title:'Code.org – AP CS Principles', desc:'Free, project-based AP CSP curriculum with visual programming activities.', url:'https://code.org/educate/csp', icon:'💻', featured:true},
  {subject:'apCSP', title:'College Board – AP CSP', desc:'Official exam info, past FRQs, sample performance tasks, score guidelines.', url:'https://apstudents.collegeboard.org/courses/ap-computer-science-principles', icon:'📋'},
  {subject:'apCSP', title:'CrashCourse Computer Science', desc:'40-episode YouTube series covering hardware, software, internet, and CS history.', url:'https://www.youtube.com/playlist?list=PL8dPuuaLjXtNlUrzyH5r6jN9ulIgZBpdo', icon:'📺'},
  {subject:'apCSP', title:'Replit – Online Coding', desc:'Browser-based coding environment — write and run Python, JavaScript, and more for free.', url:'https://replit.com', icon:'⚡'},
  {subject:'apCSP', title:'CS Field Guide', desc:'Comprehensive, interactive computer science textbook — great for deeper learning.', url:'https://www.csfieldguide.org.nz', icon:'📕'},
  // Spanish 2
  {subject:'spanish2', title:'Khan Academy – Spanish', desc:'Grammar, verb conjugations, vocabulary, and reading — structured Spanish practice.', url:'https://www.khanacademy.org/humanities/ap-spanish', icon:'🎓', featured:true},
  {subject:'spanish2', title:'SpanishDict – Dictionary & Conjugator', desc:'Best online Spanish dictionary with complete verb conjugation tables and audio.', url:'https://www.spanishdict.com', icon:'📖', featured:true},
  {subject:'spanish2', title:'Conjuguemos – Verb Practice', desc:'Focused, timed verb conjugation drills for every tense and irregular verb.', url:'https://conjuguemos.com', icon:'⚡'},
  {subject:'spanish2', title:'Duolingo – Spanish', desc:'Gamified daily Spanish practice — great for vocabulary and reading habits.', url:'https://www.duolingo.com', icon:'🦜'},
  {subject:'spanish2', title:'Dreaming Spanish', desc:'Free YouTube videos in slow, comprehensible Spanish — immersive listening practice.', url:'https://www.youtube.com/c/DreamingSpanish', icon:'👂'},
  {subject:'spanish2', title:'LanguageTransfer – Spanish Audio', desc:'Free 40-episode audio course explaining Spanish grammar from first principles.', url:'https://www.languagetransfer.org', icon:'🎧'},
];
